### ISSUE TITLE
Set a global account instead of passing it to every function

### ISSUE THREAD

**Issue by dalmemail** [bashrc/libgnusocial#2]
While is was working on #1 I was thinking that instead of passing the account argument to every function that requires it we may set a global account at libgnusocial, so the functions will work with it. I mean that usually we will be working with the same account during the time so we should just do something like: gs_account_set(account) to set it (maybe copying 'account' to a global or maybe with a pointer).

The bad 'thing' of this is that for software that works with different accounts at the same time (maybe bots or something like that) it would be a bit embarrassing to re-set the account forever.

**Comment by bashrc** [comment]
I think that multiple accounts should be supported. People often have an account on more than one instance.

**Comment by dalmemail** [comment]
My idea is that you could do something like:
```
gs_set_account(account1);
post_status(status); //posted to 'account1'
gs_set_account(account2);
post_status(status); //posted to 'account2'
```

**Comment by bashrc** [comment]
Right, but suppose you have two accounts on two instances. You want to receive posts from both within two threads.

**Comment by dalmemail** [comment]
It's true. Then you'll have to set a mutex and let one thread wait until the other one is ended (to avoid race condition). And then re-set the account. We'll left this out.
